#!/usr/bin/env bash

ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


if [ $# -eq 0 ]; then
  echo "Must determine output language: ´compile [python, dart]´"
  exit -1
fi

if [ $# -eq 1 ]; then
  OUTPUT=$1
  if [ "$OUTPUT" == "python" ]; then
    echo "Compiling for python"
  elif [ "$OUTPUT" == "dart" ]; then
    echo "Compiling for dart"
  else
    echo "Unknown output! ($OUTPUT)"
    exit -1
  fi
  
fi

BUILD_DIR=build/$OUTPUT
BUILD_PATH=$ROOT_DIR/$BUILD_DIR
ABSOLUTE=1


if [ $# -eq 2 ]; then
  BUILD_PATH=$2
  ABSOLUTE=0
fi

mkdir -p $ROOT_DIR/build
mkdir -p $ROOT_DIR/$BUILD_DIR/$OUTPUT


function buildInPath {
  for PROTO_FILE in "$1/*.proto"
  do
    echo "Processing $PROTO_FILE file..."
    #mkdir -p $BUILD_PATH/$1
    #protoc -I=$1 --python_out=$BUILD_PATH/$1 $PROTO_FILE

    if [ "$OUTPUT" == "python" ]; then
      protoc -I=$1 --python_out=$BUILD_PATH $PROTO_FILE
    elif [ "$OUTPUT" == "dart" ]; then
      protoc -I=$1 --dart_out=$BUILD_PATH $PROTO_FILE
    fi
    

  done
}


# Compile common ROS messages
buildInPath $ROOT_DIR/common

# Compile all integrations
for SUBDIR_PATH in $ROOT_DIR/integrations/*/
do
    SUBDIR_NAME=${SUBDIR_PATH%*/}      # remove the trailing "/"
    SUBDIR_NAME="${SUBDIR_NAME##*/}"    # print everything after the final "/"

    if [ $SUBDIR_NAME != $BUILD_DIR ]; then
      buildInPath $SUBDIR_PATH 
    fi
done





