# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HTTPHeaders.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11HTTPHeaders.proto\"\xdb\x05\n\x07Headers\x12\x0c\n\x04\x41_IM\x18\x01 \x01(\t\x12\x0e\n\x06\x41\x63\x63\x65pt\x18\x02 \x01(\t\x12\x16\n\x0e\x41\x63\x63\x65pt_Charset\x18\x03 \x01(\t\x12\x17\n\x0f\x41\x63\x63\x65pt_Encoding\x18\x04 \x01(\t\x12\x17\n\x0f\x41\x63\x63\x65pt_Language\x18\x05 \x01(\t\x12\x17\n\x0f\x41\x63\x63\x65pt_Datetime\x18\x06 \x01(\t\x12%\n\x1d\x41\x63\x63\x65ss_Control_Request_Method\x18\x07 \x01(\t\x12&\n\x1e\x41\x63\x63\x65ss_Control_Request_Headers\x18\x08 \x01(\t\x12\x15\n\rAuthorization\x18\t \x01(\t\x12\x15\n\rCache_Control\x18\n \x01(\t\x12\x12\n\nConnection\x18\x0b \x01(\t\x12\x16\n\x0e\x43ontent_Length\x18\x0c \x01(\r\x12\x14\n\x0c\x43ontent_Type\x18\r \x01(\t\x12\x0e\n\x06\x43ookie\x18\x0e \x01(\t\x12\x0c\n\x04\x44\x61te\x18\x0f \x01(\t\x12\x0e\n\x06\x45xpect\x18\x10 \x01(\t\x12\x11\n\tForwarded\x18\x11 \x01(\t\x12\x0c\n\x04\x46rom\x18\x12 \x01(\t\x12\x0c\n\x04Host\x18\x13 \x01(\t\x12\x10\n\x08If_Match\x18\x14 \x01(\t\x12\x19\n\x11If_Modified_Since\x18\x15 \x01(\t\x12\x15\n\rIf_None_Match\x18\x16 \x01(\t\x12\x10\n\x08If_Range\x18\x17 \x01(\t\x12\x1b\n\x13If_Unmodified_Since\x18\x18 \x01(\t\x12\x14\n\x0cMax_Forwards\x18\x19 \x01(\r\x12\x0e\n\x06Origin\x18\x1a \x01(\t\x12\x0e\n\x06Pragma\x18\x1b \x01(\t\x12\x1b\n\x13Proxy_Authorization\x18\x1c \x01(\t\x12\r\n\x05Range\x18\x1d \x01(\t\x12\x0f\n\x07Referer\x18\x1e \x01(\t\x12\n\n\x02TE\x18\x1f \x01(\t\x12\x12\n\nUser_Agent\x18  \x01(\t\x12\x0f\n\x07Upgrade\x18! \x01(\t\x12\x0b\n\x03Via\x18\" \x01(\t\x12\x0f\n\x07Warning\x18# \x01(\t')



_HEADERS = DESCRIPTOR.message_types_by_name['Headers']
Headers = _reflection.GeneratedProtocolMessageType('Headers', (_message.Message,), {
  'DESCRIPTOR' : _HEADERS,
  '__module__' : 'HTTPHeaders_pb2'
  # @@protoc_insertion_point(class_scope:Headers)
  })
_sym_db.RegisterMessage(Headers)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADERS._serialized_start=22
  _HEADERS._serialized_end=753
# @@protoc_insertion_point(module_scope)
