# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ROSResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ROSEnums_pb2 as ROSEnums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ROSResponse.proto\x1a\x0eROSEnums.proto\"r\n\x0bROSResponse\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x05.Type:\x08RESPONSE\x12\x17\n\x06method\x18\x02 \x01(\x0e\x32\x07.Method\x12\x0c\n\x04\x63ode\x18\x03 \x01(\r\x12\x0f\n\x07headers\x18\x05 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\x06 \x01(\x0c')



_ROSRESPONSE = DESCRIPTOR.message_types_by_name['ROSResponse']
ROSResponse = _reflection.GeneratedProtocolMessageType('ROSResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROSRESPONSE,
  '__module__' : 'ROSResponse_pb2'
  # @@protoc_insertion_point(class_scope:ROSResponse)
  })
_sym_db.RegisterMessage(ROSResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROSRESPONSE._serialized_start=37
  _ROSRESPONSE._serialized_end=151
# @@protoc_insertion_point(module_scope)
