# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1_btcmarket_response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bv1_btcmarket_response.proto\"\xe9\x04\n\x15v1_btcmarket_response\x12)\n\x04time\x18\x01 \x01(\x0b\x32\x1b.v1_btcmarket_response.Time\x12\x12\n\ndisclaimer\x18\x02 \x01(\t\x12\x11\n\tchartName\x18\x03 \x01(\t\x12\'\n\x03\x62pi\x18\x04 \x01(\x0b\x32\x1a.v1_btcmarket_response.Bpi\x1a>\n\x04Time\x12\x0f\n\x07updated\x18\x01 \x01(\t\x12\x12\n\nupdatedISO\x18\x02 \x01(\t\x12\x11\n\tupdateduk\x18\x03 \x01(\t\x1aZ\n\x03Usd\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\nrate_float\x18\x05 \x01(\x01\x1aZ\n\x03Gbp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\nrate_float\x18\x05 \x01(\x01\x1aZ\n\x03\x45ur\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\nrate_float\x18\x05 \x01(\x01\x1a\x80\x01\n\x03\x42pi\x12\'\n\x03USD\x18\x01 \x01(\x0b\x32\x1a.v1_btcmarket_response.Usd\x12\'\n\x03GBP\x18\x02 \x01(\x0b\x32\x1a.v1_btcmarket_response.Gbp\x12\'\n\x03\x45UR\x18\x03 \x01(\x0b\x32\x1a.v1_btcmarket_response.Eurb\x06proto3')



_V1_BTCMARKET_RESPONSE = DESCRIPTOR.message_types_by_name['v1_btcmarket_response']
_V1_BTCMARKET_RESPONSE_TIME = _V1_BTCMARKET_RESPONSE.nested_types_by_name['Time']
_V1_BTCMARKET_RESPONSE_USD = _V1_BTCMARKET_RESPONSE.nested_types_by_name['Usd']
_V1_BTCMARKET_RESPONSE_GBP = _V1_BTCMARKET_RESPONSE.nested_types_by_name['Gbp']
_V1_BTCMARKET_RESPONSE_EUR = _V1_BTCMARKET_RESPONSE.nested_types_by_name['Eur']
_V1_BTCMARKET_RESPONSE_BPI = _V1_BTCMARKET_RESPONSE.nested_types_by_name['Bpi']
v1_btcmarket_response = _reflection.GeneratedProtocolMessageType('v1_btcmarket_response', (_message.Message,), {

  'Time' : _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
    'DESCRIPTOR' : _V1_BTCMARKET_RESPONSE_TIME,
    '__module__' : 'v1_btcmarket_response_pb2'
    # @@protoc_insertion_point(class_scope:v1_btcmarket_response.Time)
    })
  ,

  'Usd' : _reflection.GeneratedProtocolMessageType('Usd', (_message.Message,), {
    'DESCRIPTOR' : _V1_BTCMARKET_RESPONSE_USD,
    '__module__' : 'v1_btcmarket_response_pb2'
    # @@protoc_insertion_point(class_scope:v1_btcmarket_response.Usd)
    })
  ,

  'Gbp' : _reflection.GeneratedProtocolMessageType('Gbp', (_message.Message,), {
    'DESCRIPTOR' : _V1_BTCMARKET_RESPONSE_GBP,
    '__module__' : 'v1_btcmarket_response_pb2'
    # @@protoc_insertion_point(class_scope:v1_btcmarket_response.Gbp)
    })
  ,

  'Eur' : _reflection.GeneratedProtocolMessageType('Eur', (_message.Message,), {
    'DESCRIPTOR' : _V1_BTCMARKET_RESPONSE_EUR,
    '__module__' : 'v1_btcmarket_response_pb2'
    # @@protoc_insertion_point(class_scope:v1_btcmarket_response.Eur)
    })
  ,

  'Bpi' : _reflection.GeneratedProtocolMessageType('Bpi', (_message.Message,), {
    'DESCRIPTOR' : _V1_BTCMARKET_RESPONSE_BPI,
    '__module__' : 'v1_btcmarket_response_pb2'
    # @@protoc_insertion_point(class_scope:v1_btcmarket_response.Bpi)
    })
  ,
  'DESCRIPTOR' : _V1_BTCMARKET_RESPONSE,
  '__module__' : 'v1_btcmarket_response_pb2'
  # @@protoc_insertion_point(class_scope:v1_btcmarket_response)
  })
_sym_db.RegisterMessage(v1_btcmarket_response)
_sym_db.RegisterMessage(v1_btcmarket_response.Time)
_sym_db.RegisterMessage(v1_btcmarket_response.Usd)
_sym_db.RegisterMessage(v1_btcmarket_response.Gbp)
_sym_db.RegisterMessage(v1_btcmarket_response.Eur)
_sym_db.RegisterMessage(v1_btcmarket_response.Bpi)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _V1_BTCMARKET_RESPONSE._serialized_start=32
  _V1_BTCMARKET_RESPONSE._serialized_end=649
  _V1_BTCMARKET_RESPONSE_TIME._serialized_start=180
  _V1_BTCMARKET_RESPONSE_TIME._serialized_end=242
  _V1_BTCMARKET_RESPONSE_USD._serialized_start=244
  _V1_BTCMARKET_RESPONSE_USD._serialized_end=334
  _V1_BTCMARKET_RESPONSE_GBP._serialized_start=336
  _V1_BTCMARKET_RESPONSE_GBP._serialized_end=426
  _V1_BTCMARKET_RESPONSE_EUR._serialized_start=428
  _V1_BTCMARKET_RESPONSE_EUR._serialized_end=518
  _V1_BTCMARKET_RESPONSE_BPI._serialized_start=521
  _V1_BTCMARKET_RESPONSE_BPI._serialized_end=649
# @@protoc_insertion_point(module_scope)
